image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - betterthantomorrow.calva

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore

github:
  prebuilds:
    main: true

tasks:
  - name: jayfu setup
    init: |
      # We want to install this from .gitpod.Dockerfile, but some bug prevents it
      brew install borkdude/brew/babashka
    command: |
      # Open instructions in VS Code
      code README.md
